import { StyleSheet } from 'react-native';

export const circleStyles = StyleSheet.create({
  scroll: { flex: 1 },
  content: { padding: 16, paddingBottom: 24, gap: 16 },
  header: { gap: 2 },
  headerLabel: { letterSpacing: 2, textTransform: 'uppercase' },
  headerTitle: { letterSpacing: -0.5 },
  card: { borderRadius: 20, padding: 16, borderWidth: 1 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  cardHeaderLabel: { letterSpacing: 2, textTransform: 'uppercase' },
  membersBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999 },
  membersBadgeText: { letterSpacing: 0.5 },
  avatarsRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  avatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontWeight: '700' },
  addBtn: { width: 40, height: 40, borderRadius: 20, borderWidth: 2, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center' },
  addBtnText: { fontSize: 20, lineHeight: 20 },
  circleMessage: { lineHeight: 18 },
  sectionLabel: { letterSpacing: 2, textTransform: 'uppercase', marginBottom: 10 },
  journeyList: { gap: 8 },
  journeyCard: { borderRadius: 20, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  journeyTitle: {},
  journeySubtitle: { marginTop: 2 },
  journeyEmoji: { fontSize: 24 },
  expertCard: { borderRadius: 20, padding: 16, borderWidth: 1 },
  expertRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  expertAvatar: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  expertAvatarText: { fontWeight: '700' },
  expertName: {},
  expertSub: {},
});
