import { StyleSheet } from 'react-native';

export const profileStyles = StyleSheet.create({
  scroll: { flex: 1 },
  content: { padding: 16, paddingBottom: 32, gap: 14 },
  header: { gap: 2 },
  headerLabel: { letterSpacing: 2, textTransform: 'uppercase' },
  headerTitle: { letterSpacing: -0.5 },
  menuItem: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, padding: 14, borderWidth: 1 },
  menuIconWrap: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  menuIconInner: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  menuIconText: { fontWeight: '700' },
  menuTextWrap: { flex: 1, minWidth: 0 },
  menuLabel: {},
  menuSub: { marginTop: 1 },
  menuChevron: { fontSize: 14 },
  themeRow: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 20, padding: 14, borderWidth: 1 },
  themeIconWrap: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 20, borderWidth: 1 },
  logoutText: {},
  legalText: { textAlign: 'center', paddingBottom: 8 },
  // Journey switcher
  sectionBlock: { gap: 8 },
  sectionTitle: { letterSpacing: 2, textTransform: 'uppercase', paddingHorizontal: 4 },
  journeyGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  journeyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    borderWidth: 1.5,
    paddingHorizontal: 14,
    paddingVertical: 9,
    position: 'relative',
  },
  journeyChipEmoji: { fontSize: 14 },
  journeyChipLabel: {},
  journeyActiveIndicator: {
    position: 'absolute',
    bottom: -1,
    left: '50%',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FFFFFF',
  },
});

